default: true

heading-increment: false
first-line-h1: false
ul-style:
  style: dash
ul-indent:
  indent: 2
line-length: false
no-inline-html: false
emphasis-style:
  style: asterisk
fenced-code-language: false
no-blanks-blockquote: false
