name: Comment to issue workflow
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create issues from TODO comments
        uses: alstr/todo-to-issue-action@v4
